name: disl

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: 'Build dockerfile'
      run: |
        docker build . --tag wemake-services/docker-image-size-limit:latest

    - uses: wemake-services/docker-image-size-limit@master
      with:
        image: 'wemake-services/docker-image-size-limit:latest'
        size: 405MB
